http://localhost:5118/movies

### 

http://localhost:5118/movies?forKidsOnly=true&minimumRating=7&availableOnCd=true

###

POST http://localhost:5118/ticketPurchases/children/4

###

POST http://localhost:5118/moviePurchases/cd/1